(function(){
  try{if(typeof ids!=='undefined'&&!ids.includes('quote'))ids.push('quote')}catch(e){}
  const review=document.getElementById('review');
  if(review&&!document.getElementById('quote')){
    review.insertAdjacentHTML('beforebegin',`<section id="quote" class="hidden"><div class="sectionTop"><button class="back" onclick="loadAccount()">← Volver</button><button class="home" onclick="show('home')">🏠 Inicio</button></div><div class="card"><h2>Enviar presupuesto</h2><div id="quoteFor" class="sub">El precio lo define el profesional. RESOLVÉ no calcula ni fija valores.</div><label class="label">Monto estimado (ARS)</label><input id="quoteAmount" class="field" type="number" min="1" step="1" placeholder="Ej.: 85000"><label class="label">Detalle del presupuesto</label><textarea id="quoteMessage" class="field" rows="4" placeholder="Qué incluye, materiales, tiempos u observaciones"></textarea><button class="green" onclick="submitQuote()">ENVIAR PRESUPUESTO</button><div id="quoteOk" class="ok hidden">✅ Presupuesto enviado. El cliente ya puede verlo.</div></div></section>`)
  }
  window.openQuote=function(id,name){window.__quoteRequestId=id;document.getElementById('quoteAmount').value='';document.getElementById('quoteMessage').value='';document.getElementById('quoteOk').classList.add('hidden');document.getElementById('quoteFor').textContent='Presupuesto para '+(name||'el cliente')+'. El precio lo definís vos.';show('quote')};
  window.submitQuote=async function(){const amount=Number(document.getElementById('quoteAmount').value);if(!amount||amount<=0)return alert('Ingresá el monto del presupuesto.');const msg=document.getElementById('quoteMessage').value.trim();const {error}=await sb.from('service_requests').update({quote_amount:amount,quote_message:msg,status:'quoted',quoted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',window.__quoteRequestId);if(error)return alert('No pudimos enviar el presupuesto: '+error.message);document.getElementById('quoteOk').classList.remove('hidden')};
  window.loadAccount=async function(){const u=await getUser();if(!u)return show('login');const {data:p}=await sb.from('profiles').select('id,role,full_name,zone,trade').eq('id',u.id).maybeSingle();document.getElementById('accountIdentity').textContent=(p?.full_name||u.email)+' · '+(p?.role==='professional'?'Profesional':p?.role==='admin'?'Administrador':'Cliente');let html='';const {data:reqs}=await sb.from('service_requests').select('id,trade,zone,description,status,professional_id,client_id,client_name,client_phone,client_email,quote_amount,quote_message,quoted_at,created_at').order('created_at',{ascending:false});if(reqs?.length){const statusEs={pending:'Pendiente',accepted:'Aceptado',quoted:'Presupuestado',completed:'Completado',cancelled:'Cancelado'};html+='<h3>Solicitudes de presupuesto</h3>'+reqs.map(r=>{const isPro=p?.role==='professional'&&r.professional_id===u.id;const phone=String(r.client_phone||'').replace(/\D/g,'');return `<div class="proCard"><b>${esc(r.trade)} · ${esc(r.zone)}</b><div class="meta">Estado: ${esc(statusEs[r.status]||r.status)} · ${new Date(r.created_at).toLocaleDateString('es-AR')}</div><div class="mini">${esc(r.description)}</div>${r.quote_amount?`<div class="info" style="margin-top:10px"><b>Presupuesto:</b> $ ${Number(r.quote_amount).toLocaleString('es-AR')}<br>${r.quote_message?esc(r.quote_message):''}</div>`:''}${isPro?`<div class="mini" style="margin-top:10px"><b>Cliente:</b> ${esc(r.client_name||'Sin nombre')}<br>📱 ${esc(r.client_phone||'Sin WhatsApp')}<br>✉️ ${esc(r.client_email||'Sin email')}</div>${phone?`<a class="green" style="display:block;text-align:center;text-decoration:none;margin-top:10px" target="_blank" rel="noopener" href="https://wa.me/54${phone}">CONTACTAR POR WHATSAPP</a>`:''}`:''}${isPro&&r.status!=='completed'?`<button class="primary" onclick="openQuote('${r.id}','${esc(r.client_name||'Cliente')}')">${r.status==='quoted'?'ACTUALIZAR PRESUPUESTO':'ENVIAR PRESUPUESTO'}</button><button class="green" onclick="markCompleted('${r.id}')">MARCAR TRABAJO COMPLETADO</button>`:''}${r.client_id===u.id&&r.status==='quoted'?`<div class="ok">✅ Tenés un presupuesto nuevo del profesional.</div>`:''}${r.client_id===u.id&&r.status==='completed'?`<button class="green" onclick="openReview('${r.id}','${r.professional_id}')">VALORAR PROFESIONAL</button>`:''}</div>`}).join('')}
    const {data:apps}=await sb.from('job_applications').select('id,status,created_at,job_id,job_posts(title,company)').eq('applicant_id',u.id).order('created_at',{ascending:false});if(apps?.length)html+='<h3 style="margin-top:18px">Mis postulaciones</h3>'+apps.map(a=>`<div class="proCard"><b>${esc(a.job_posts?.title||'Puesto')}</b><div class="meta">${esc(a.job_posts?.company||'')} · ${esc(a.status)}</div></div>`).join('');document.getElementById('activity').innerHTML=html||'<div class="sub">Todavía no tenés actividad.</div>';if(p?.role==='professional')document.getElementById('activity').insertAdjacentHTML('afterend','<button id="editProBtn" class="secondary" onclick="editProfessional()">EDITAR MI PERFIL PROFESIONAL</button>');show('account')};
})();