// RESOLVÉ v3 — circuito de contratación
let selectedProfessional=null;
function resolveStatusLabel(s){return ({pending:'Solicitud enviada',quoted:'Presupuesto recibido',accepted:'Presupuesto aceptado',completed:'Trabajo completado'}[s]||s||'Pendiente')}
async function resolveOpenProfessional(p){selectedProfessional=p;go('professional');$('professionalDetail').innerHTML='<span class="badge">'+safe(p.trade||'Profesional')+'</span><h2>'+safe(p.full_name)+'</h2>'+(p.zone?'<p>📍 '+safe(p.zone)+'</p>':'')+(p.rating?'<p class="stars">★ '+Number(p.rating).toFixed(1)+' · '+Number(p.review_count||0)+' valoraciones</p>':'<p>Profesional nuevo en RESOLVÉ</p>')+(p.bio?'<p class="lead">'+safe(p.bio)+'</p>':'');let rr=await resolveProfessionalReviews(db,p.id);$('professionalReviews').innerHTML=rr.data?.length?rr.data.slice(0,5).map(x=>'<div class="item"><span class="stars">★ '+x.rating+'</span>'+(x.comment?'<p>'+safe(x.comment)+'</p>':'')+'</div>').join(''):'<div class="msg">Todavía no tiene valoraciones.</div>'}
async function resolveSubmitRequest(){if(!session)return go('guest');if(profile?.role==='professional')return msg('requestMsg','Ingresá con una cuenta de cliente para solicitar un presupuesto.');let description=$('requestDescription').value.trim();let zone=$('requestZone').value.trim()||selectedProfessional?.zone||'';if(!description||!zone)return msg('requestMsg','Contanos qué necesitás y en qué zona.');let r=await resolveCreateServiceRequest(db,{clientId:session.user.id,clientName:profile?.full_name||session.user.email,clientPhone:profile?.phone||'',clientEmail:session.user.email,professionalId:selectedProfessional.id,trade:selectedProfessional.trade||'Servicio',zone,description});msg('requestMsg',r.error?r.error.message:'✓ Solicitud enviada. El profesional ya puede presupuestarla.');if(!r.error)$('requestDescription').value=''}
async function resolveQuoteAction(id){let amount=prompt('Ingresá el monto del presupuesto');if(!amount)return;let note=prompt('Mensaje para el cliente (opcional)')||'';let r=await resolveSendQuote(db,id,session.user.id,Number(amount),note);if(r.error)alert(r.error.message);else openAccount()}
async function resolveAcceptAction(id){let r=await resolveAcceptQuote(db,id,session.user.id);if(r.error)alert(r.error.message);else openAccount()}
async function resolveCompleteAction(id){let r=await resolveCompleteRequest(db,id,session.user.id,profile?.role);if(r.error)alert(r.error.message);else openAccount()}
async function resolveReviewAction(req){let rating=Number(prompt('Calificá de 1 a 5 estrellas'));if(!rating)return;let comment=prompt('Dejá un comentario (opcional)')||'';let r=await resolveCreateReview(db,{clientId:session.user.id,professionalId:req.professional_id,requestId:req.id,rating,comment});if(r.error)alert(r.error.message);else{alert('¡Gracias por tu valoración!');openAccount()}}
function resolveRenderActivity(rows){if(!rows?.length)return '<div class="msg">Todavía no hay actividad.</div>';return rows.map(x=>{let actions='';if(profile?.role==='professional'&&x.status==='pending')actions='<button onclick="resolveQuoteAction(\''+x.id+'\')">Enviar presupuesto</button>';if(profile?.role!=='professional'&&x.status==='quoted')actions='<button onclick="resolveAcceptAction(\''+x.id+'\')">Aceptar presupuesto</button>';if(x.status==='accepted')actions='<button onclick="resolveCompleteAction(\''+x.id+'\')">Marcar trabajo completado</button>';if(profile?.role!=='professional'&&x.status==='completed'&&x.professional_id)actions='<button onclick=\'resolveReviewAction('+JSON.stringify({id:x.id,professional_id:x.professional_id})+')\'>Valorar profesional</button>';return '<div class="item"><span class="badge">'+safe(resolveStatusLabel(x.status))+'</span><br><b>'+safe(x.trade)+'</b><p>'+safe(x.description)+'</p><small>📍 '+safe(x.zone)+'</small>'+(x.quote_amount?'<p><b>Presupuesto: $'+Number(x.quote_amount).toLocaleString('es-AR')+'</b></p>':'')+(x.quote_message?'<p>'+safe(x.quote_message)+'</p>':'')+actions+'</div>'}).join('')}
